source 'https://rubygems.org'

gem 'jekyll'
gem 'github-pages'
gem 'jekyll-seo-tag'
gem 'jekyll-coffeescript'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-feed'
gem 'jekyll-minifier'
gem 'html-proofer'
